#!/usr/bin/env python3
import os
import sys


sys.stdin = open("/dev/tty", "r")
gitStatusChecked = 0
while gitStatusChecked == 0:
    print("Did you add all the files needed for the commit? \n")
    os.system('git status')
    choice = input("awaiting input(y/n): ")

    if choice.lower() == 'n':
        files = input("Enter space separated file names(enter blank to proceed without add): ")
        if files.strip() == "":
            gitStatusChecked = 1
            continue
        try:
            os.system('git add ' + files)
        except Exception as e:
            print(e.message)

    else:
        gitStatusChecked = 1

print("Check the diff for the commit?(y/n)")
choice = input()
if choice.lower() == 'y':
  os.system(' git diff head')
  choice = input("all good?(y/n): ")
else:
  exit(0)

if choice.lower() == 'n':
    print("Make sure your diff is correct and commit again")
    exit(1)

else:
    exit(0)
